name = "nomejodas-web"
compatibility_flags = ["nodejs_compat", "cache_option_enabled"]
compatibility_date = "2024-09-23"
pages_build_output_dir = "build"


[vars]
TOGETHER_AI_KEY="f817d19e2b5b7b8190d85c2414f8e4cb2e740b81eb59fd283babe2d0faba8715"
OPENAI_API_KEY="f817d19e2b5b7b8190d85c2414f8e4cb2e740b81eb59fd283babe2d0faba8715"
UPSTASH_VECTOR_REST_TOKEN="ABkFMGNoYW1waW9uLXdhbHJ1cy0xMTIwOC11czFhZG1pbllqYzVZVFV6WldJdFlqQmxPUzAwTnpBd0xXSTVZekl0TkRsbE1EbG1ZMlJsWVdWaA=="
UPSTASH_VECTOR_REST_URL="https://champion-walrus-11208-us1-vector.upstash.io"
PUBLIC_BASE_URL="https://nomejodasweb.pages.dev"
